### ISSUE TITLE
Implement Radix Sort

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#10]
Steps:

- Insert your script in algs.py
- Add in algorithmDict: 'algorithm Name : algorithm function'
- Insert 'handleDrawing(array, redBar, redBar, blueBar, blueBar)' to the deepest section of the algorithm
(The parameters are the array and bars indexes)

**Comment by aswarth123** [comment]
I would to take this issue can you assign it to me?

**Comment by LucasPilla** [comment]
If you have another algorithm in mind to be implemented open an issue, Thanks for helping!
