### ISSUE TITLE
[BUG]Array size input validation

### ISSUE THREAD

**Issue by m3et** [LucasPilla/Sorting-Algorithms-Visualizer#105]
Array Size input validation
Input size is not validate causing program to crash when input size of array is to big ~100000000 or 0 or none
labels: user-experience
assignees: 'Self-assigned' 

I will change the code to make validation on the size to be in range (0,500000)

![image](https://user-images.githubusercontent.com/50811873/121070069-ed1d9600-c7d6-11eb-8eb0-d17b0dbc1bae.png)

**Comment by LucasPilla** [comment]
Thanks for reporting it! I appreciate your help.

**Comment by m3et** [comment]
NP, I'm thinking about a assigning a defualt value if int() function trhow an exeption.
ley me now what you this?

![image](https://user-images.githubusercontent.com/50811873/121072107-746c0900-c7d9-11eb-8a00-932b68f5c4ec.png)

**Comment by m3et** [comment]
Hey, this seemes to be working.
![image](https://user-images.githubusercontent.com/50811873/121075532-f3634080-c7dd-11eb-8532-b4724eb8056b.png)

Its kind of my first time so I'm not sure what should I do in order to make a pull request...

**Comment by LucasPilla** [comment]
@m3et Hello! You might find something if you search for how to open a pull request. If you have any problem let me know.

**Comment by sandipan898** [comment]
Is this issue still open to fix or someone has already fixed it?

**Comment by LucasPilla** [comment]
@sandipan898 The problem was fixed, just waiting for @m3et to open a pull request with his changes
