### ISSUE TITLE
Suggestion: Might need to add documentation on which version of python to run

### ISSUE THREAD

**Issue by mdemichele** [LucasPilla/Sorting-Algorithms-Visualizer#107]
Is the program intended to be run with python 3 or python 2? 

As I was attempting to run the program for the first time, I had to change a few pieces of syntax to get the program to work with the python version 2.7.15 that I was using. Specifically, I had to make three changes: 

1.) Changed any instance of the super() function in the display.py file from super() to super(subclassName, self) 

2.) Changed a function definition in combSort.py from def get_gap(prev_gap) -> int:  to def get_gap(prev_gap):

3.) Changed the order of the arguments in the shellSort() function in the shellSort().py file. 

The program worked just fine after making those couple of syntax changes. I'm sure it would've worked fine if I was running python3, but you might want to add some documentation letting new users know which version of python to use with the program. 

I'd be happy to add to the documentation if you think that's a needed addition!

**Comment by LucasPilla** [comment]
@mdemichele Thanks for reporting. Yes, it must run with python 3, i would appreciate your help!

**Comment by mdemichele** [comment]
No problem, I just submitted a pull request with the changes to the README. 

I think it's literally as simple as specifying to users to use:
`python3 main.py` 

instead of:
`python main.py`
