### ISSUE TITLE
Suggestion:- How about showing algorithm name, time complexity wise?

### ISSUE THREAD

**Issue by vthz** [LucasPilla/Sorting-Algorithms-Visualizer#114]
**- DESCRIPTION**
A feature in which you can choose time complexity(Average) from drop down menu which updates the algorithm list dynamically to accommodate only those algorithm with chosen time complexity!!!

**-How it could be implemented?**
Store Algorithm names and time complexity in _algorithmDict_, make a list(_timeComplexityOpt_) of various time complexities and update both of them in drop down menu box. Now check in every update, if Time Complexity box got some new TC, take current TC, and send it to returnAlgoList(current) which will compare and return all algorithm having that time complexity as list.

**- Are you up to do it?-**
- >I have already implemented this feature and sent a Pull Request.

**-Note**
1. This is my first contribution to Github Repositories.
2. You can see images in Pull Request " Show Algorithms according to selected time complexity(New Feature)".
3. I can take care of minor fixes in new code.
4. Really love to hear about my work. #feedback

**Comment by LucasPilla** [comment]
Hey @vthz, I will have a look! Thanks!
