### ISSUE TITLE
Turning Sorting Functions into Generators

### ISSUE THREAD

**Issue by GlacialBlaze** [LucasPilla/Sorting-Algorithms-Visualizer#124]
@mugulmd

Let our first step be changing sorting functions into generators. Can we make a branch of the original code where only the functions are changed, so that we can see how the generators would perform on the original code?

**Comment by mugulmd** [comment]
Yeah sure I can just make a new fork of the master branch and make the changes, I can take care of that later today if that's okay with you :)
