### ISSUE TITLE
 Restructure the code

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#13]
Currently: 
- There is a file "algs.py" with all algorithms in it.

How it should be: 
- Each algorithm in a unique file.
- The file algs.py must contain the algorithmsDict and the function runAlgorithm, ONLY.

**Comment by utsav00** [comment]
Seems doable and easy. May I work on this?

**Comment by LucasPilla** [comment]
For sure!
