### ISSUE TITLE
Implement Patience Sort

### ISSUE THREAD

**Issue by nclsbayona** [LucasPilla/Sorting-Algorithms-Visualizer#140]
Hi. I was checking all of this and It seems like patience sort is not implemented, I already have this done and would love to contribute with it. [Wikipedia explanation](https://en.wikipedia.org/wiki/Patience_sorting)

**Comment by LucasPilla** [comment]
Sure!

**Comment by nclsbayona** [comment]
Hey, can this be pulled?
