### ISSUE TITLE
Implement Scroll Menu

### ISSUE THREAD

**Issue by GlacialBlaze** [LucasPilla/Sorting-Algorithms-Visualizer#143]
@mugulmd

Hey! It's been awhile since we left off our progress in the menu design. Free to make a scroll menu?

**Comment by mugulmd** [comment]
Hi @GlacialBlaze !
Sorry I'm deep into some other projects I'm not gonna have time...

**Comment by GlacialBlaze** [comment]
No worries, it's fine. 😊

**Comment by Sohaib90** [comment]
I can help if this issue is still active

**Comment by LucasPilla** [comment]
Hey @Sohaib90. It's been a while since I worked on this project, but I would appreciate your help!

**Comment by Sohaib90** [comment]
I can try looking into it. Do you remember what this enhancement was and what were you aiming for?
