### ISSUE TITLE
Implement Double Selection Sort

### ISSUE THREAD

**Issue by ealfla8** [LucasPilla/Sorting-Algorithms-Visualizer#147]

**Comment by kadeep47** [comment]
hey ! I would like to work on this algo can u assign this to me.

**Comment by Sabine91** [comment]
isnt double selection sort just cocktail sort, but good job @kadeep47 your code is good.

**Comment by 72002sweta** [comment]
may i work on  it

**Comment by LucasPilla** [comment]
@72002sweta This task has already been done.
