### ISSUE TITLE
Compress GIFs

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#152]
`Task`: the gifs are quite heavy so I want to optimize/compress them.

**Comment by highb33kay** [comment]
Hi @LucasPilla , How do i get started?

**Comment by LucasPilla** [comment]
@highb33kay To be honest I don't have idea 🤣

**Comment by highb33kay** [comment]
@LucasPilla okay, 😂. I am on it anyway.

**Comment by highb33kay** [comment]
Hi @LucasPilla. I didnt realize you changed the topic already. I was waiting to be assigned lol. I will get right to it now.

**Comment by tuhinmallick** [comment]
Is this issue still open then I would like to work on it

**Comment by LucasPilla** [comment]
@tuhinmallick The task is quite simple, just compress the gifs

**Comment by AnshMasand** [comment]
is the issue open? I can finish it

**Comment by tuhinmallick** [comment]
@LucasPilla I have made a PR for the issue

**Comment by LucasPilla** [comment]
@tuhinmallick Thank you for contributting!
