### ISSUE TITLE
Organize repo

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#153]
`Task`:
- Create a new directory called `res` with all files from `gifs` and `images` folder.
- Create a new directory called `src` that contains the `.py` files and `algorithms` folder
- Make sure to update the `README.md` and `CONTRIBUTING.md` with the correct new paths.

**Comment by ArturoEmmanuelToledoAguado** [comment]
Hello ✌ I am from mexico and i would like to help you with this task. 😄

**Comment by LucasPilla** [comment]
Sure, feel free to ask me anything! 😄
