### ISSUE TITLE
Create a .gitignore file

### ISSUE THREAD

**Issue by utsav00** [LucasPilla/Sorting-Algorithms-Visualizer#16]
#### Reason:
- Adding individual files for tracking becomes tedious as the repository grows
- We don't need to track pycache folders and other IDE config files

#### How to do:
.gitignore files are readily available on the internet, all you have to do is look up the appropriate content and copy-paste it

**Comment by LucasPilla** [comment]
I am totally new to managing repositories, can you help?

**Comment by LucasPilla** [comment]
I created the requirements.txt and .gitignore, I would appreciate if you have a look to see if i did it right

**Comment by utsav00** [comment]
Looks good!
Though what we usually do is just copy-paste the .gitignore for python (read as whatever language you're using); and in github, there is an option to init .gitignore at the time of creating a repo and you can select Python at that time only! :smile:

**Comment by utsav00** [comment]
Also, mention the issue number in the commit message when directly pushing to master branch, so that you can see the commit here automatically!

**Comment by LucasPilla** [comment]
Thanks for helping me, you did a great job restructuring the code and gave me all this advices!
