### ISSUE TITLE
Update algorithms options

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#162]
Some algorithms don't run in-place, so it doesn't make sense to "visualize" them. I need to check if it is possible to do the sorting in-place, otherwise remove it from the list to be selected.

**Comment by shivamAmrutia** [comment]
@LucasPilla i could give it a try if its ok

**Comment by LucasPilla** [comment]
Sure!

**Comment by zen1405** [comment]
@LucasPilla if you still need more people, I'd love to give this a shot as well.

**Comment by LucasPilla** [comment]
@zen1405 I dont know what @shivamAmrutia has done so far, but you could help as well.
I think its better if you comment here on which algorithms you are working.

**Comment by raghavaraghav3** [comment]
Hey @LucasPilla . can you assign this to me?

Thanks,
Ven

**Comment by S-Eemani** [comment]
Hey @LucasPilla would like to work on this. @raghavaraghav3 let me know if I can help with anything.

**Comment by jayitasaha40** [comment]
Hello @LucasPilla, I'm new to open source & would like to work on this. @raghavaraghav3 let's work & learn together if you're comfortable.

**Comment by BlacPharaoh** [comment]
Hi, I am new to open source. I am interested in working on this. can you assign it to me. lets learn and work

**Comment by atishay2305-hub** [comment]
Hi, can I try this issue if it is still available to contribute to?

**Comment by skbedi** [comment]
Hi, I would love to contribute to this issue.

**Comment by LucasPilla** [comment]
Hey @skbedi, this issue has been completed. Feel free to contribute with other issues or open an issue if you have some idea. I will open some issues as well, you can contribute to them if you wish.
