### ISSUE TITLE
Add some docstrings / comments explainning each sorting algorithm

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#164]
Please, choose an avaiable algorithm and comment it's name before you start working.

Algorithms:
- [ ] bogoSort
- [ ] bitonicSort
- [ ] binaryinsertionSort
- [ ] bubbleSort
- [ ] heapSort
- [ ] gnomeSort
- [ ] cycleSort
- [ ] countingSort
- [ ] combSort
- [ ] cocktailSort
- [ ] bucketSort
- [ ] timSort
- [ ] strandSort
- [ ] stoogeSort
- [ ] shellSort
- [ ] selectionSort
- [ ] quickSort
- [ ] pigeonholeSort
- [ ] pancakeSort
- [ ] oddevenSort
- [ ] mergeSort
- [ ] insertionSort
- [ ] radixSort
- [ ] treeSort
- [ ] exchangeSort

**Comment by lucasrafaldini** [comment]
Hey, I want to contribute with binaryinsertionSort docstrings.

**Comment by lucasrafaldini** [comment]
I took the liberty to also make the docstrings for bitonicSort. Here's the PR -> https://github.com/LucasPilla/Sorting-Algorithms-Visualizer/pull/165

**Comment by lucasrafaldini** [comment]
Hey guys.

I took advantage of the holidays in Brazil and wrote docstrings for all algorithms. I hope it helps.
I tried to keep a certain "standard" but sometimes I didn't know everything about it or just didn't know anything to write about but I think they are a good starting point.

**Comment by LucasPilla** [comment]
I will have a look asap, thanks! 😄

**Comment by Velin-Todorov** [comment]
Hi. Is this issue still open? Are there algorithms that still need comments/docstrings?

**Comment by LucasPilla** [comment]
@Velin-Todorov, @lucasrafaldini did a great job :wave:  but there are some tasks to be done: 
- maybe it is better if we keep the docstrings 1 or 2 paragraphs long.
- add a simple table with time and space complexity for each algorithm.
- remove the "Args" and "Yields" parts, they are not useful at all

What do you think?

**Comment by Velin-Todorov** [comment]
It sounds great. Please assign this to me.
Where can i find the docstrings?

Also, could you please provide me with a deadline?

Kind regards,

Velin

**Comment by LucasPilla** [comment]
@Velin-Todorov I just merged the pull request made by @lucasrafaldini. 
- Now you can find the docstrings in this repository ([src/algorithms](https://github.com/LucasPilla/Sorting-Algorithms-Visualizer/tree/master/src/algorithms)).
- Take your time and fell free to ask anything.

**Comment by raghavaraghav3** [comment]
> @Velin-Todorov, @lucasrafaldini did a great job 👋 but there are some tasks to be done:
> 
> * maybe it is better if we keep the docstrings 1 or 2 paragraphs long.
> * add a simple table with time and space complexity for each algorithm.
> * remove the "Args" and "Yields" parts, they are not useful at all
> 
> What do you think?

Hey @LucasPilla  can you also assign this to me?? I can work on some of the algorithms.

Thanks,
Ven

**Comment by Velin-Todorov** [comment]
> > @Velin-Todorov, @lucasrafaldini did a great job 👋 but there are some tasks to be done:
> > 
> > * maybe it is better if we keep the docstrings 1 or 2 paragraphs long.
> > * add a simple table with time and space complexity for each algorithm.
> > * remove the "Args" and "Yields" parts, they are not useful at all
> > 
> > What do you think?
> 
> Hey @LucasPilla can you also assign this to me?? I can work on some of the algorithms.
> 
> Thanks, Ven

> > @Velin-Todorov, @lucasrafaldini did a great job 👋 but there are some tasks to be done:
> > 
> > * maybe it is better if we keep the docstrings 1 or 2 paragraphs long.
> > * add a simple table with time and space complexity for each algorithm.
> > * remove the "Args" and "Yields" parts, they are not useful at all
> > 
> > What do you think?
> 
> Hey @LucasPilla can you also assign this to me?? I can work on some of the algorithms.
> 
> Thanks, Ven

Hi Ven. I prefer to work this task alone.

Kind regards,

Velin

**Comment by Velin-Todorov** [comment]
@LucasPilla I have finished editing the docstrings. Let me know what you think. Tomorrow I will add the table with the complexities as well.

**Comment by brkuhgk** [comment]
@Velin-Todorov can you highlight the sorting algorithms which are not contributed.
