### ISSUE TITLE
Suggestion : Displaying the values of the bars for better visualization and understanding

### ISSUE THREAD

**Issue by tkgowtham** [LucasPilla/Sorting-Algorithms-Visualizer#168]
- Idea :
 I would like to display the values of the bars that are being sorted just right below it, so it will be easier for user to understand what values are being sorted and how the sorting works in that particular algorithm.

- How it could be implemented : 
 This could be implemented by adding a box right below the bar. We could display the values of the bar respectively there. In each iteration, the values would move along with the red bar to show the user, how the algorithm sorts the values. 

  It would also be diffcult to display values of larger size or larger count of values, since they can intersect each other, so we will also have to be able to give user the accessibilty to resize the window.

- I would like to do this if you want to implement my suggestion.

**Comment by LucasPilla** [comment]
@tkgowtham I like the idea, but I don't think it will look good with a lot of bars. Maybe we should add this feature if number of bars 
 is less then X, what do you think?

**Comment by tkgowtham** [comment]
Yes, I agree with your point. We can assume X to be less than or equal to 50. So, can I work on it ? If so, pls assign me to this issue.

**Comment by dan424gg** [comment]
I would like to be assigned to this issue.

@LucasPilla

**Comment by dhruva2000** [comment]
Hey I can work on this I have some ideas for how to implement this

**Comment by LucasPilla** [comment]
Sure @dhruva2000, this issue is quite simple, we just need to find some way to show the bar values. Maybe just showing the values when the number of bars is small, otherwise  it might get too cluttered.

**Comment by dhruva2000** [comment]
Got it thank you!

**Comment by dhruva2000** [comment]
Just attached my pull request onto this @LucasPilla! . I incorporated some of the changes from the previously opened pull request and added values to the bars again so I'm hoping this successfully captures the suggestion by @tkgowtham. I also added some padding and shifted some of the components to create more visual clarity in the app
