### ISSUE TITLE
Implementing time taken to sort

### ISSUE THREAD

**Issue by SunnyWan59** [LucasPilla/Sorting-Algorithms-Visualizer#169]
It would be interesting and helpful to see the time an algorithm takes to sort visualized on the bottom display.

**Comment by adrienneli104** [comment]
Is this issue still open? I would like to work on it if so

**Comment by aaravtanti** [comment]
Hi, I would like to contribute to this issue.

**Comment by SunnyWan59** [comment]
I think I finished it in my pull request

**Comment by LucasPilla** [comment]
Hey @aaravtanti, @SunnyWan59 has already completed the issue, but you could contribute to his pull request #170 if you wish.
It would be cool to have the time updated with each iteration, instead of just displaying it at the end.
