### ISSUE TITLE
typo: remove the comment in algs.py

### ISSUE THREAD

**Issue by utsav00** [LucasPilla/Sorting-Algorithms-Visualizer#17]
I forgot to remove the comment for the `handleDrawing`. It is not being imported in the algs.py, so remove it.

**Comment by aswarth123** [comment]
I will remove it assign it to me

**Comment by LucasPilla** [comment]
@utsav00 Thanks for notifying and  @aswarth123 for the disposition, but i will fix that 
through the PR for Radix Sort.
