### ISSUE TITLE
Bug: Exchange sort throws TypeError

### ISSUE THREAD

**Issue by nanashi-03** [LucasPilla/Sorting-Algorithms-Visualizer#173]
- Describe your issue
When "exchange sort" is visualized it's throwing a type error and exiting.
![image](https://github.com/LucasPilla/Sorting-Algorithms-Visualizer/assets/40239873/f55663cf-9739-4d8d-8386-16d6a4d7961b)

- How it could be fixed?
I could try some error handling and checking if the algorithm runs then. If not I can try fixing it.

- Are you up to do it?
Yes.

**Comment by aminechm** [comment]
#174
