### ISSUE TITLE
Improve main.py and remove hardcoded values from display.py

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#176]
- Make main.py more readable by adding some comments
- Remove hardcoded values from display.py and move all global definitions to another file (a new one or main.py)

**Comment by LucasPilla** [comment]
Sure @PedramHaeri, when you're done I can assign the other one to you if it is still free.

**Comment by hlai1** [comment]
Hi @LucasPilla! I know @PedramHaeri is assigned to this issue but I've just submitted a PR (#183) to solve the issues listed in this. Please take a look if you have some time!

**Comment by sebas-inf** [comment]
As the issue seems to still be open could I be assigned the issue?

**Comment by Manishmrgn** [comment]
Hi @LucasPilla I would like to contribute to this issue. Could I be assigned to this issue?

**Comment by Devn913** [comment]
The issue is still open. Is anyone trying, or Can I try?

**Comment by Dxuian** [comment]
is this still open ?
