### ISSUE TITLE
Adding hacktoberfest topic to repository

### ISSUE THREAD

**Issue by aewens** [LucasPilla/Sorting-Algorithms-Visualizer#19]
### Subject of the issue
A recent update has made hacktoberfest opt-in via adding a topic to the repository (due to the spam issue on unsuspecting repos). For PRs to count for the issues flagged as being for hacktoberfest, the topic needs to be added to the repository as well. See here for more details:

https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by LucasPilla** [comment]
I will fix that!
