### ISSUE TITLE
Add a speed option (slow, normal or fast)

### ISSUE THREAD

**Issue by Darius-ss10** [LucasPilla/Sorting-Algorithms-Visualizer#191]
Hello,

I would like to add a speed option (slow, normal or fast) in order to enhance a little bit the application. I think that that being able to change the execution speed, would allow some users to visualize a little bit better how the sorting algorithms work.

**Comment by Darius-ss10** [comment]
@LucasPilla Can I please get assigned to this issue?

**Comment by LucasPilla** [comment]
@Darius-ss10 It would be great to have a slider to set the speed. We used to have it (as shown in the image) but I removed because it wasn't well modularized, do you thing you can implement it?

![f88c67bbf47a233d72b769a3db2fe74d](https://github.com/user-attachments/assets/ec755082-1591-43eb-aac3-f4d3c4ba7fe8)

**Comment by Darius-ss10** [comment]
@LucasPilla I've initially thought to implement it as a dropdown menu (just like the sort algorithm choice) where the user could choose the speed he wanted between several options. I'll try to implement the slider but if I won't be able to do it properly I will implement this feature as a dropdown menu. Is that ok for you?

**Comment by LucasPilla** [comment]
@Darius-ss10 Hmm, I'm not sure about having a dropdown just to select the speed, I think a slider is better.

I was thinking about implementing a toggle switch to change the visualization between bars and points. Let me know if you would be interested on that.

**Comment by Darius-ss10** [comment]
@LucasPilla Ok I'll do the slider then. This being said, I have one more question : is there any license linked to this project or not? (If I'm not mistaken, I haven't seen any on the main page of this repository)

**Comment by LucasPilla** [comment]
I added the LICENSE file (https://github.com/LucasPilla/Sorting-Algorithms-Visualizer/blob/master/LICENSE) , it is MIT License.
