### ISSUE TITLE
Change the color selection for drawing the bars

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#20]
Currently it is possible to draw 2 red bars and 2 blue bars, which are passed as parameters to the handleDrawing function.
The idea is to pass lists, maybe intervals, as parameters such that all the elements in it will assume a especific color.

**Comment by Mikhaylov-yv** [comment]
We can add green for the sorted bars. Like [here](https://www.youtube.com/watch?v=ZZuD6iUe3Pc)
I'll try to do this.

**Comment by LucasPilla** [comment]
The idea for this issue is change the way a bar color is selected, so it would be easier to insert more colors in more complex algorithms, currently we are limited by 2 colors!  After that i would be concerned about the colors themselves. If you fix that or make the visulaization more educational and clear for beginners, just do it! I appreciate.

**Comment by LucasPilla** [comment]
Do you think we should keep a single function for drawing the bars and colors, or have one for each algorithm?

**Comment by LucasPilla** [comment]
I tried your modifications for this issue (Green bars), they worked pretty well, but I was thinking to paint in green just the bars that the algorithms consider to be sorted. For exemple, in case a bar happens to be sorted without the algorithm pass
through her, in your implementation this bar would be green. Let me know what is your opinion.

**Comment by Mikhaylov-yv** [comment]
I don't understand yet where the algorithm says that the bar is sorted.
My implementation is independent and may show algorithm errors.
Although I may not understand everything yet.
I'll try to understand tomorrow

**Comment by prmurphy** [comment]
@Mikhaylov-yv Would you like any help with this issue?

**Comment by Mikhaylov-yv** [comment]
@prmurphy Yes of course.

**Comment by prmurphy** [comment]
@Mikhaylov-yv is this the kind of behavior were expecting. (Except the bars should stay green after completion; and the first bat should also be green.). https://www.youtube.com/watch?v=26jBKCdy57s

**Comment by Mikhaylov-yv** [comment]
@prmurphy @LucasPilla Yes. It looks good

**Comment by prmurphy** [comment]
@Mikhaylov-yv 
Ok, I'm going to try to think of the best way to implement this. So far I rewrote drawBars to include an array or sorted rows.
Of course that means well have to rewrite every call to 'handleDrawing' to include 'greenBar'. I think it might be better to rewrite drawBars to include kwargs so we dont have to rewrite every algorithm. Let me know what you think.

def drawBars(array, redBar1, redBar2, blueBar1, blueBar2, greenBar):
    """Draw the bars and control their colors"""
    for num in range(numBars):
        print(greenBar)
        print(num)
        if num in [redBar1, redBar2]:
            color = red
        elif num in [blueBar1, blueBar2]:
            color = blue
        elif num in greenBar:
            color = green
        else:
            color = grey
        bar_width = 900/numBars
        pygame.draw.rect(screen, color, [num * bar_width, 400 - array[num]

**Comment by LucasPilla** [comment]
@prmurphy It looks great! We'll have to rewrite anyway, right? So we can add the  bars to the sorted list according to each algorithm.  But if you manage to make it easier would be helpful.

**Comment by prmurphy** [comment]
Here what I ended up with for 'drawBars'
`def drawBars(array, redBar1, redBar2, blueBar1, blueBar2, **kwargs):
    """Draw the bars and control their colors"""    
    for num in range(numBars):
        if num in [redBar1, redBar2]:
            color = red
        elif num in [blueBar1, blueBar2]:
            print(blueBar1, blueBar2)
            color = blue
        
        elif "greenRows" in kwargs and (num in (kwargs['greenRows'])):      
            color = green        
        else:
            color = grey
        bar_width = 900/numBars
        pygame.draw.rect(screen, color, [num * bar_width, 400 - array[num], ceil(bar_width), array[num]])`

I'll try to get the pull request in tonight after some testing

**Comment by prmurphy** [comment]
`def drawBars(array, redBar1, redBar2, blueBar1, blueBar2, **kwargs):
    """Draw the bars and control their colors"""    
    for num in range(numBars):
        if num in [redBar1, redBar2]:
            color = red
        elif num in [blueBar1, blueBar2]:            
            color = blue
        
        elif "greenRows" in kwargs and (num in (kwargs['greenRows'])):      
            color = green        
        else:
            color = grey
        bar_width = 900/numBars
        pygame.draw.rect(screen, color, [num * bar_width, 400 - array[num], ceil(bar_width), array[num]])`

**Comment by prmurphy** [comment]
@LucasPilla @Mikhaylov-yv I just submitted a pull request. I only added the green bars while sorting to the insertionSort.py file.
