### ISSUE TITLE
Add default values

### ISSUE THREAD

**Issue by Mikhaylov-yv** [LucasPilla/Sorting-Algorithms-Visualizer#21]
I got this error here: "ValueError: invalid literal for int() with base 10: ''"

[main.py](https://github.com/LucasPilla/Sorting-Algorithms-Visualizer/blob/master/main.py)
32`                    display.numBars = int(display.sizeBox.text)`

Tell me what am I doing wrong?

**Comment by LucasPilla** [comment]
Currently the program does not handle errors, so if you insert some non digit caracters it will broke! If you did all right you must have found some exception. Anyway, thanks for reporting this issue.

**Comment by LucasPilla** [comment]
I would appreciate your feedback about the program, and if you intend to help as well!

**Comment by Mikhaylov-yv** [comment]
Yes, I'm ready to help.

I made a clone of your project. And crunched **main.py**. But I did not understand what parameters need to be entered for the program to work.
Or should I add an algorithm file to the project?

**Comment by LucasPilla** [comment]
You managed to open the program with the size, delay, algorithm and play buttom?
If you did it you just have to insert valid values, e.g. 450 in size, 0 in delay, Mergesort in algorithm and press the play buttom

**Comment by Mikhaylov-yv** [comment]
I'm sorry everything works!
Let me add the default parameters.
This will make it easier to understand how the program works.

**Comment by LucasPilla** [comment]
Sure, I will asign this issue to you! If you manage a way to handle this errors, so when a user forgets this parameters or insert them wrong the program does not broke i would appreciate as well.

**Comment by Mikhaylov-yv** [comment]
I don't understand why such a diff turns out.
It looks like this to me:
![dif](https://user-images.githubusercontent.com/44315225/95108151-8f1a4980-0743-11eb-88d4-835bde799d17.png)

**Comment by LucasPilla** [comment]
Are you up to change the code for handle possible errors?

**Comment by Mikhaylov-yv** [comment]
Yes of course

**Comment by LucasPilla** [comment]
Its working well, but it would be more efficient if the default values were defined just once outside the loop, right? Its not necessary to keep verifying and neither create a bool variable.

**Comment by Mikhaylov-yv** [comment]
Oh sure. I'll fix it now.

**Comment by LucasPilla** [comment]
I will close this issue and merge the pull request that you add default values
