### ISSUE TITLE
Any idea, feedback or bug?

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#25]
I would appreciate some feedback, ideas and bug reports about this program.

**Comment by Mikhaylov-yv** [comment]
You can see my commit. 78c164cc5ee345947313374a0a8f8e50cd37d23e
My idea is melting:
If the data in **display.sizeBox** or **display.algorithmBox** is not correct. The egg color changes to red.
But I have one problem. I don't know how to change the color in the display.sizeBox.

**Comment by LucasPilla** [comment]
I see your problem, I did the module for these input Boxes a time ago and there are a lot of harded code. When i have a time I will improve this module in a way that you can easily access the box properties, e.g. sizeBox.color = some_color.

**Comment by egurnick** [comment]
It seems that display.py references the wrong folders for playButton and stopButton.
It references data/..
But should reference images/..

**Comment by LucasPilla** [comment]
I forgot to change, thanks for remenbering

**Comment by Mikhaylov-yv** [comment]
Hey. I made the selection red, you can see it in my branch.
https://github.com/Mikhaylov-yv/Sorting-Algorithms-Visualizer/tree/error_checking

**Comment by LucasPilla** [comment]
Thanks, there are some problems but the error alert is working! I still want to remake the code for input boxes so the code keeps clear and simple! For this reason I wont be merging your pull request right now

**Comment by Mikhaylov-yv** [comment]
yes, it also seems to me that the code has become worse to read.

**Comment by LucasPilla** [comment]
@Mikhaylov-yv  There are  a lot to improve but i already did some changes! I rewrote the class for input boxes, especially in the method that updates the boxes values and I made the play button an instance of InputBox! The main.py is much cleaner to read, i hope :).
I made the seletion red as well, for that i just change the color atribute for the input boxes inside the error_checking function that you implemented!
I would appreciate if you could give me a feedback

**Comment by Mikhaylov-yv** [comment]
@LucasPilla I believe this works great

**Comment by prmurphy** [comment]
When installing on Windows I get the following error.

C:\Users\steve\Sorting-Algorithms-Visualizer>pip install -r requirements.txt
Collecting pygame==1.9.6
  Using cached pygame-1.9.6.tar.gz (3.2 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\steve\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\steve\\AppData\\Local\\Temp\\pip-install-hyaxeunf\\pygame\\setup.py'"'"'; __file__='"'"'C:\\Users\\steve\\AppData\\Local\\Temp\\pip-install-hyaxeunf\\pygame\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\steve\AppData\Local\Temp\pip-pip-egg-info-0dd9hpg2'
         cwd: C:\Users\steve\AppData\Local\Temp\pip-install-hyaxeunf\pygame\
    Complete output (17 lines):


    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using WINDOWS configuration...


    Download prebuilts to "prebuilt_downloads" and copy to "./prebuilt-x64"? [Y/n]Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\steve\AppData\Local\Temp\pip-install-hyaxeunf\pygame\setup.py", line 194, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "C:\Users\steve\AppData\Local\Temp\pip-install-hyaxeunf\pygame\buildconfig\config.py", line 210, in main
        deps = CFG.main(**kwds)
      File "C:\Users\steve\AppData\Local\Temp\pip-install-hyaxeunf\pygame\buildconfig\config_win.py", line 576, in main
        and download_win_prebuilt.ask(**download_kwargs):
      File "C:\Users\steve\AppData\Local\Temp\pip-install-hyaxeunf\pygame\buildconfig\download_win_prebuilt.py", line 302, in ask
        reply = raw_input(
    EOFError: EOF when reading a line
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 20.3.3 is available.
You should consider upgrading via the 'c:\users\steve\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

**Comment by LucasPilla** [comment]
I think the problem is related to python and ygame versions that are not compatible.
Try installing pygame this way: ```pip install pygame``` and let me know if it worked.

**Comment by LucasPilla** [comment]
Both ways, specifying or not the version, worked for me.

**Comment by prmurphy** [comment]
@LucasPilla  It worked after I ran `pip install pygame`, which installed 'pygame-2.0.1-cp39-cp39-win_amd64.whl'. When trying to install from requirements.txt it attempted to intsall pygame-1.9.6.tar.gz which I really doubt works with windows. Thanks for the help.

**Comment by LucasPilla** [comment]
Great! Thanks for reporting this error, as a temporary and simple solution i will remove the version specification from requirements.txt.

**Comment by prmurphy** [comment]
When you run bogosort, if you hit the 'stop' button the program freezes. I'm not exactly sure how the 'stop' button works, so I dont know what's causing this.

**Comment by LucasPilla** [comment]
Actually the stop button stops the drawing, this makes the process faster.
Because bogosort is an "algorithm" extremely eneficient, it takes forever to finish.

**Comment by Lorretje** [comment]
- Maybe get rid of the 'sort' name part in each algorithm. This would, I think, make the selection of algorithm more readable.

- Else, make sure all algorithm names end with 't' (Some names may be too long to display?)
