### ISSUE TITLE
Implement Cocktail Sort

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#3]
Steps:
- Insert your script in algs.py
- Add in algorithmDict: 'algorithm Name : algorithm function'
- Insert 'handleDrawing(redBar, redBar, blueBar, blueBar)' to the deepest section of the algorithm 
(The parameters are bars indexes)

**Comment by aswarth123** [comment]
I would like to add the cocktail sort can you assign this issue to me.

**Comment by LucasPilla** [comment]
Sure! Just pointing out that i am new to Python Programming so there must have some bad coding practices, feel free to make changes or ask me anything.

**Comment by aswarth123** [comment]
Ok surely I will get back to you incase of an issue

**Comment by LucasPilla** [comment]
Closing Issue #3
