### ISSUE TITLE
 Distinguish algorithms with variants

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#35]
- Suggestion (@lucblassel )
In algorithms with variants, like Shell Sort, should have a way to the user select an variant to be visualized.
- How it could be implemented:
Add a Input Box, like a drop list, in front of algorithm selection box.
- Are you up to do it?
I @LucasPilla will be working on this, feel free to contribute!

**Comment by jmsby** [comment]
Hi, I'm completely new to github and trying to using this issue as an chance to help figure it out. I made a fork that can group variants, but wasn't sure how all the variants should be grouped so I've only added the bubblesort variants as an example. https://github.com/jmsby/Sorting-Algorithms-Visualizer/tree/variants
If you've got any suggestions on the grouping or improvements I could make that'd be great

**Comment by LucasPilla** [comment]
@jmsby  You are totally welcome to contributting! 😄 
I tested your changes and that was exactly what I previously had in mind! But now I am not sure if this feature would help or confuse, what do you think?

**Comment by jmsby** [comment]
I thought the same as I tested before committing it so I've regrouped them into types and given an all option, I think it's adds educational value and isn't too confusing.

**Comment by jmsby** [comment]
Just put in a pull request #85, if theres anything I can do to improve it just let me know

**Comment by LucasPilla** [comment]
@jmsby  It looks a little confuse to me, can you try grouping them by time complexity?

**Comment by jmsby** [comment]
If you intended to do an info section on each algorithim I think the time complexity and type of algorithim would fit in nicely 
I'll see if I can come up with a solution to make it less complex this week, but it seems to me like any grouping may be more confusing than none.

**Comment by Lorretje** [comment]
Hi guys, have you considered implementing a categorisation with a table or at least mentioning the Big O efficiency?
For example, see [Big O Cheatsheet](https://www.bigocheatsheet.com/). I guess this would be a bonus feature.

![image](https://user-images.githubusercontent.com/73077357/108505856-532dee00-72b8-11eb-9e24-1c248af0cbb2.png)

**Comment by LucasPilla** [comment]
@Lorretje It would be a nice feature. Maybe when selecting the algorithm it shows these complexities.

**Comment by GlacialBlaze** [comment]
In my opinion, including variants of a sorting algorithm will go a long way in contributing to the sorting research.

For example, shellsort has many variants in its gap calculation and this has opened up deep studies into its internal workings. The race to improve is on. 

Another is quicksort. Quicksort has a few variants like left-left pointers, left-right pointers, stable version, and others. Each of them has their own unique approach to sorting despite the same concept. While shellsort variants merely have different gaps resulting in little dramatic difference, quicksort variants are different in mechanisms such that when **visualised** show dramatic differences. So, as a visualiser, it would a big plus point for us.

Easier said than done, but if we can show variants of the same sort, it would make this visualiser stand out from the crowd.

**Comment by yashjain0** [comment]
We can create a tree of subtypes and different variations of sorting like on
[whimsical.com](https://whimsical.com/sorting-9vFKvNbrmkNGxHxsanSd96)
and add links to them, like this 
![Sorting](https://user-images.githubusercontent.com/62240937/116033738-93766780-a67f-11eb-84f3-a099e3d844d9.png)

**Comment by patrick-bedkowski** [comment]
Hi, I am new to open source project contributions. I've seen your project listed for help-wanted and since I am interested in the topic of sorting algorithms I decided to write here. Can I be of any assistance?

**Comment by LucasPilla** [comment]
@patrick-bedkowski Hey! If you have any ideas to improve the program, I would appreciate your help.
If you are comfortable with some of the open issues or unfinished pull requests, please feel free to contribute.

**Comment by LucasPilla** [comment]
@patrick-bedkowski The ideia through this issue is to allow the user to select the algorithm by time complexity, and show this information in the program.

**Comment by Andrey2Kovalev** [comment]
I added a 'Complexity' Box near to 'Algorithm' selector box with complexity of each algorithm. First, the complexity is selected, then the sorting algorithm. A variant with a tree, as @yashjain0 wrote. If this is still relevant, I can send my edits.

**Comment by LucasPilla** [comment]
@Andrey2Kovalev 
Hey, can you open a pull request? So I can see what you've done.
Thanks for contributing btw

**Comment by Andrey2Kovalev** [comment]
I have created a new request:
addedComplexityBox #146
