### ISSUE TITLE
Implement Bitonic Sort

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#36]
- Implement the algorithm
- Insert it in a file bitonicSort.py inside algorithms directory
- In algorithms/\_\_init\_\_.py:
Import yout algorithm: `from algorithms.bitonicSort import bitonicSort`
Add it to \_\_all\_\_: `"bitonicSort",`

If you manage to use the handleDrawing function I would appreciate!

**Comment by shubhamnag14** [comment]
can i solve this issue..

**Comment by LucasPilla** [comment]
Sure!
