### ISSUE TITLE
Implement Comb Sort

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#38]
- Implement the algorithm
- Insert it in a file combSort.py inside algorithms directory
- In algorithms/\_\_init\_\_.py:
       Add: `from algorithms.combSort import combSort`
       Add in \_\_all\_\_: "combSort",
- Add `combsort` to `algorithmsDict` in algs.py
If you manage to use the `handleDrawing` function I would appreciate!

**Comment by aolaria** [comment]
Hi, could you please assign this to me?

**Comment by LucasPilla** [comment]
Sure!
