### ISSUE TITLE
Implement Gnome Sort

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#39]
- Implement the algorithm 
- Insert it in a file gnomeSort.py inside algorithms directory
- In algorithms/\_\_init\_\_.py:
       Add: `from algorithms.gnomeSort import gnomeSort`
       Add in \_\_all\_\_: "gnomeSort",
- Add `gnomesort` to `algorithmsDict` in algs.py
If you manage to use the `handleDrawing` function I would appreciate!

**Comment by egurnick** [comment]
Hi, can you please assign this to me?

**Comment by LucasPilla** [comment]
Sure!
