### ISSUE TITLE
Make this pygame program a executable

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#44]
If possible I would like to make this pygame program a unique executable, using pyinstaller for exemple!
I tried working with pyintaller but had no success.

**Comment by Ares358** [comment]
Apparently you'll need to put **display.py** and the **images folder** in the same directory as the generated **main.exe** file for it to work. The following should be helpful if you want to include those into the exe
https://stackoverflow.com/questions/7674790/bundling-data-files-with-pyinstaller-onefile/13790741#13790741

**Comment by LucasPilla** [comment]
Thanks for the advice!
