### ISSUE TITLE
Make a GIF for each sorting algorithm

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#45]
The idea is basically record a gif for all sorting algorithms, with the same delay and size, to replace the GIFS from [github wiki page](https://github.com/LucasPilla/Sorting-Algorithms-Visualizer/wiki)

**Comment by vanigupta20024** [comment]
The Gifs in the [https://github.com/LucasPilla/Sorting-Algorithms-Visualizer/wiki](githubwiki page) seem good to me, why are they to be replaced?

**Comment by asinghgaba** [comment]
Hey! This looks a fairly easy task and I think I can do it. Let me know if you want me to work on it, I'll be happy to do it.

**Comment by LucasPilla** [comment]
Sure!

**Comment by asinghgaba** [comment]
@LucasPilla I've done the changes but can't figure it how to open a pull request for the wiki. The link for my repo is [HERE](https://github.com/asinghgaba/Sorting-Algorithms-Visualizer-Wiki)

**Comment by LucasPilla** [comment]
Unfortunately there is no way to open a pr for the wiki page! 
@asinghgaba I'm so sorry, I thought i had specified the size and I forgot to insert an exemple.
I would chose a size of 200 and the gif should contain just the bars, example:
![mergesort](https://user-images.githubusercontent.com/64286128/106538175-9b889600-64da-11eb-8da3-b872950a16b1.gif)
I appreciate what you did, it must have taken you some time to record those gifs. I would be so thankful if you remake it.
Anyway, i will manage some way to insert you as a contributor.

**Comment by asinghgaba** [comment]
Okay no problem I’ll do that by tonight and let you know once it’s done.

**Comment by asinghgaba** [comment]
UPDATE @LucasPilla the changes are done, tbh it looks much cleaner now.

**Comment by LucasPilla** [comment]
@asinghgaba  Wow, it looks incredible!
Can I use your repository as a ofical way to contribute in wiki page? So if anyone wants to contribute they will commit to your repo.

**Comment by asinghgaba** [comment]
Thank you @LucasPilla
Yh no problem at all.

**Comment by LucasPilla** [comment]
@asinghgaba Can you open a pull request to my repo adding a folder with all gifs?

**Comment by asinghgaba** [comment]
Okay, I'll do it now.
