### ISSUE TITLE
As apart from python language, c++ is most widely used in cse applications, also this language is easily understandable by students (as they are familair with C), so can i contribute by implementing important visualizer sorting algorithm in c++ or JAVA

### ISSUE THREAD

**Issue by niharika11031997** [LucasPilla/Sorting-Algorithms-Visualizer#46]
- Describe your idea
- How it could be implemented (optional)
- Are you up to do it?

**Comment by LucasPilla** [comment]
I am not looking for sorting algorithms in other languages because it would no be possible to visualize them with this pygame program. But I appreciate your intention :)
