### ISSUE TITLE
Implement [shell sort]

### ISSUE THREAD

**Issue by niharika11031997** [LucasPilla/Sorting-Algorithms-Visualizer#47]

**Comment by niharika11031997** [comment]
i'm implementing this

**Comment by LucasPilla** [comment]
See what i wrote in the other issue!

**Comment by niharika11031997** [comment]
I'm saying that I can implement shell sort in python only as in wiki nobody
has contributed in it

**Comment by LucasPilla** [comment]
Ahhh, i just realized that the wiki is outdated, sorry about that. The shell sort algorithm was already implemented, check algorithms folder.
