### ISSUE TITLE
Add sounding for the sorting visualization

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#48]
I would like to add audibilization, but I don't know if it's possible without harming the frame rate or anythink alike.
I appreciate your help!

**Comment by bansaljas** [comment]
Hey, 
I'd like to try working on this enhancement!

Thanks

**Comment by bansaljas** [comment]
Hello,
So I have successfully added the background music, but do you want the sound to sync with the way the algorithm goes about with the visualization? If you anything specific in mind, please let me know, I'll try incorporating that.

Thanks!

**Comment by LucasPilla** [comment]
@bansaljas Hey, it would be really cool if the sound were synced with the sorting, if you manage to do this I appreciate.

**Comment by bansaljas** [comment]
Sure, I am trying to figure that out!

**Comment by bansaljas** [comment]
Hey!
So after checking and experimenting, I figured that pygame doesn't provide a mechanism to sync the sound with the visualization. For that we'll have to create different sound files using a third party audio editing app. So should I just update the code which adds the background sound?

Let me know, thanks!

**Comment by LucasPilla** [comment]
@bansaljas That will be harder than I thought. Its not necessary to add background sound.

**Comment by bansaljas** [comment]
Okay then! Thanks :)

**Comment by LucasPilla** [comment]
@bansaljas I am closing this issue now! I appreciate your help, if you want to become a "oficial" contributor just make a pull request with some irrelevant commit.
