### ISSUE TITLE
Implement Bogo Sort

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#5]
Check Repository Wiki page, or algs.py, to see algorithms already implemented!
Steps:

- Insert your script in algs.py
- Add in algorithmDict: 'algorithm Name : algorithm function'
- Insert 'handleDrawing(redBar, redBar, blueBar, blueBar)' to the deepest section of the algorithm
(The parameters are bars indexes)

**Comment by LucasPilla** [comment]
@aewens The best algorithm hahaha! I have to do some fixes and then i will merge you pull request!

**Comment by nikhil05-code** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by LucasPilla** [comment]
The other guy already did it! Thank you anyway.
If you have another algorithm in mind or intend to help somehow just create an issue

**Comment by LucasPilla** [comment]
I have a problem related to the stop button! In the moment when it is pressed the drawing process stops, so in reality the algorithm keeps working until the sorting is done.
The problem about that is when we have slow algorithms or the bogoSort, which makes the process take a long time.
Therefore the idea is to stop the drawing and the algorithm, and maybe print the sorted array!
If you manage to fix that, feel free to do it!
