### ISSUE TITLE
Implement drop List to select algorithm

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#50]
Currently you have to write the algorithm name to run it, eg: mergesort, the idea is to make a drop list that shows all algorithms and the user can select just by pressing it!
Use pygame preferably, but if you find a much easier and cleaner way do it!

**Comment by yuchenliu15** [comment]
I wanna work on this if possible?

**Comment by LucasPilla** [comment]
Okay, i will asign this issue to you
