### ISSUE TITLE
Add a Pause/Play feature

### ISSUE THREAD

**Issue by system1970** [LucasPilla/Sorting-Algorithms-Visualizer#62]
I would like to add a `Pause/Play` feature, It would be pretty useful and convenient.

**Comment by LucasPilla** [comment]
Sure, That would be really good!

**Comment by LucasPilla** [comment]
I will asign this issue to you

**Comment by system1970** [comment]
Does it need any improvement?

**Comment by LucasPilla** [comment]
It could not be better! What do you think about letting the user change delay and algorithm when paused? I may implement those features as soon i have time.
