### ISSUE TITLE
Implement Strand Sort

### ISSUE THREAD

**Issue by luckyboy-27** [LucasPilla/Sorting-Algorithms-Visualizer#64]
I can not import my module strand sort in the file __init__.py, the terminal show import error

**Comment by LucasPilla** [comment]
Could you take a print and send me?

**Comment by apurvai007** [comment]
@LucasPilla Hello, can I take up this issue?? I think I can implement the Strand Sort algorithm.
This my first time here (in open source contribution).

**Comment by LucasPilla** [comment]
Hey @apurvai007, you are totally welcome!
I assigned this issue to @luckyboy-27 some time ago, i dont know how he is doing, but fell free to implement it!
If you have any doubts fell free to ask me.

**Comment by apurvai007** [comment]
@LucasPilla i have sent a pull request, please review. I think everything is working fine.Thanks
