### ISSUE TITLE
Nit: Wrong Credit

### ISSUE THREAD

**Issue by yuchenliu15** [LucasPilla/Sorting-Algorithms-Visualizer#70]
Sorry to bother, just wanted to let you know the credit is wrong ( I did the one on the left): 

![image](https://user-images.githubusercontent.com/43976449/105250805-34a8cb80-5b2f-11eb-8207-8e3276d79a07.png)

**Comment by LucasPilla** [comment]
Im sorry! Fixing right now!

**Comment by yuchenliu15** [comment]
@LucasPilla thank you!
