### ISSUE TITLE
Improve repository website

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#74]
I would appreciate any help to improve the repository website

**Comment by yuchenliu15** [comment]
@LucasPilla the wiki site?

**Comment by LucasPilla** [comment]
@yuchenliu15 
Link: https://lucaspilla.github.io/Sorting-Algorithms-Visualizer/
The files are in another branch: https://github.com/LucasPilla/Sorting-Algorithms-Visualizer/tree/gh-pages

**Comment by SecretJuice** [comment]
I'm new to open source, but I might be able to try my hand at this. What sort of improvements do you have in mind?

**Comment by LucasPilla** [comment]
@SecretJuice Some improvements in appearance! Also I was thinking to add the visualization gifs in a 'grid', if possible.

**Comment by SecretJuice** [comment]
@LucasPilla Thanks for the info! I'll do what I can.
