### ISSUE TITLE
More Efficient List Creation

### ISSUE THREAD

**Issue by GlacialBlaze** [LucasPilla/Sorting-Algorithms-Visualizer#83]
The following code snippet is the generation of a list:

![image](https://user-images.githubusercontent.com/67182916/107346999-52e76300-6b00-11eb-9b25-81a33cf4d3b2.png)

One way would be `numbers = [randint(10, 400) for i in range(display.numBars)]`. This is more efficient than the function approach.

**Comment by LucasPilla** [comment]
@GlacialBlaze Could you implement these changes and make a pull request? This way you become a 'official' contributor
