### ISSUE TITLE
Program Interface

### ISSUE THREAD

**Issue by GlacialBlaze** [LucasPilla/Sorting-Algorithms-Visualizer#88]
This is the current display:

![image](https://user-images.githubusercontent.com/67182916/108494336-5f2ea580-72e2-11eb-9e8d-6111d5408099.png)

This is my suggestion:

![image](https://user-images.githubusercontent.com/67182916/108494256-44f4c780-72e2-11eb-93fd-7ed7045840a3.png)

For algorithms:
1. It does not overlap things at its back
2. It is scalable when more algorithms are introduced
3. It is more orderly and tidy

For the action buttons, the play becomes pause when sorting and vice versa. The stop button is always there so that at any state, the user can opt to finish it.

**Comment by LucasPilla** [comment]
@GlacialBlaze It looks great! This algorithms slide window would be constantly open?

**Comment by GlacialBlaze** [comment]
1. Sorry to push your hopes high, its just an idea I 'drew' not 'coded'. I cannot be assigned to do this as I have not touched on Pygame seriously.

2. About the slide window being constantly open, that's up to you. Should also consult others to see if they can improve on this or have even better ways.

**Comment by GlacialBlaze** [comment]
Another suggestion:

![image](https://user-images.githubusercontent.com/67182916/108589269-9a8bab80-7398-11eb-8614-efc20d9eb068.png)

In future, the program should advance to a stage where we can select the ordering of data such as 'sorted', 'reversed', 'few unique', 'random', 'partially sorted', and etc..

**Comment by GlacialBlaze** [comment]
If performance is not an issue:

![image](https://user-images.githubusercontent.com/67182916/108590117-cad54900-739c-11eb-9d0d-87c5bc402a1d.png)

Information on number of comparisons and swaps can be shown at the top left of the bar plot.

**Comment by LucasPilla** [comment]
@GlacialBlaze  These changes would be really good! Thanks for the suggestion!.

**Comment by GlacialBlaze** [comment]
@LucasPilla I'm unsure of your progress in the scroll-down algorithm box, but my observation is that creating the scroll down shares the same concept and implementation as the `Delay slider`. Making it vertical and changing its appearance to a page scroll would effectively get us a proper menu scroll. So the existing delay slider can be a headstart.

**Comment by GlacialBlaze** [comment]
@LucasPilla 

Latest idea:

![image](https://user-images.githubusercontent.com/67182916/113203825-1681e900-929f-11eb-95d0-171401c02174.png)

Advantages:
1) Almost spaces are cramped with information - visually convenient
2) Hybrid menu (pop-up + scroll-down) - compact, practical, versatile
3) Sort statistics at the bottom - bars will not overlap it (compared to previous versions)
4) Changing variables (size, play button, etc.) are kept to one side - good for navigation (compared to previous versions)

Challenges:
1) Hybrid menu is difficult to create

**Comment by GlacialBlaze** [comment]
With added light/dark mode:

![image](https://user-images.githubusercontent.com/67182916/113379996-a1e9a000-93ad-11eb-88b0-681d2be81002.png)

**Comment by rx112358** [comment]
@GlacialBlaze how does the hybrid menu look visually(for both options)? is the sort menu overlaying the entire right column

**Comment by GlacialBlaze** [comment]
@rx112358

The hybrid menu is actually what you see in the picture above. Before clicking on 'Sort' box, there is no list of choices. When you click, the choices will appear on the right as how a 'drop-down' menu would and the menu itself is a 'scroll-down' menu.

**Comment by mugulmd** [comment]
Hey everyone, 
This issue looks quite interesting, can I help ?
I'm new to open source but I've been coding in Python for a while now, and even though I'm not familiar with pygame it doesn't seem too complicated.
I could start with @GlacialBlaze  1st idea to see how we could implement a scrolling bar, or dive directly into the 2nd idea (which would probably be better but require a little more time), what would you prefer ?

**Comment by rx112358** [comment]
Hey, could I work on the hybrid menu? I begun with creating the vertical slider

**Comment by LucasPilla** [comment]
Hey @mugulmd and @rx112358 !  Are you able to manage it and work together? Maybe @rx112358 could work on the vertical slider and @mugulmd on the interface as proposed by @GlacialBlaze. What do you think?

**Comment by rx112358** [comment]
Sounds good to me. I could work on the hybrid menu.

**Comment by mugulmd** [comment]
Nice to meet you @rx112358 !
Fine by me, I can work on the side and bottom panels.

**Comment by rx112358** [comment]
> Improvements to the interface:
> 
> ![image](https://user-images.githubusercontent.com/67182916/131810906-15937083-eb27-4ed5-a919-c05143d7adf2.png)
> 
> * Themes are unrelated to sorting but rather color tastes and will be placed, as a minor option, on the top left
> * Sort menu uses color contrast

A suggestion, could an icon with color be used instead of the text for the themes?
It would be less space consuming, if the text could be replaced with an alternative
![theme](https://user-images.githubusercontent.com/53977169/132201402-c4428262-dba9-4bf4-a30d-128e14dd117f.png)

**Comment by GlacialBlaze** [comment]
That's a creative idea to save space. I support it.

In fact, it looks slightly similar to the 'L' and 'D' circles that I suggested prior to the theme menu.

Thanks.

**Comment by rx112358** [comment]
Could the theme option be a pop up if there are many themes? 
Depending on the number of themes, if there are more than three themes I think a pop up menu would keep the interface cleaner

**Comment by GlacialBlaze** [comment]
> 
> 
> Could the theme option be a pop up if there are many themes?
> Depending on the number of themes, if there are more than three themes I think a pop up menu would keep the interface cleaner
> In the image above, the box is shown as the pop up menu when the user clicks the circle.

Actually, it *is* a pop-up menu. On start, the theme menu is just as it is, a lonely little menu sitting at the top left. It's only when the user clicks on it that it will have friends below it for the user to choose.

Oh, I think I did not clarify that in my previous post. So sorry.

**Comment by LucasPilla** [comment]
I dont think having a lot of themes makes sense for a sorting algortihms visualizer, it just looks like we are adding useless features. I think we should add just a toggle button that changes between two themes (light/dark), going futher is not necessary. What do you think @rx112358 @GlacialBlaze?
![image](https://user-images.githubusercontent.com/64286128/132231006-197bc488-aa1c-4b13-a5d1-f2475f9b2616.png)

**Comment by LucasPilla** [comment]
The main idea is to make the interface as clean as possible, just showing what in necessary, like algorithm name and sorting time. If the user wants to change size, delay or visualization type (we just have one btw), they could open an slide window and change these values.

**Comment by rx112358** [comment]
> I dont think having a lot of themes makes sense for a sorting algortihms visualizer, it just looks like we are adding useless features. I think we should add just a toggle button that changes between two themes (light/dark), going futher is not necessary. What do you think @rx112358 @GlacialBlaze?
> ![image](https://user-images.githubusercontent.com/64286128/132231006-197bc488-aa1c-4b13-a5d1-f2475f9b2616.png)

A toggle button would be good i think, minimal and easier for user and drawing

**Comment by GlacialBlaze** [comment]
@LucasPilla 

There's another thing I have been thinking:

![image](https://user-images.githubusercontent.com/67182916/132235586-0955d787-2b84-48ce-9b15-4281016cdd85.png)

Would you prefer the visualizer to show such information to the user?

**Comment by rx112358** [comment]
> @LucasPilla
> 
> Oh, since we are sticking to only two themes, yes a little toggle button would be exactly enough.

simplify the toggle button to show only the colors? no icons?

**Comment by GlacialBlaze** [comment]
Well removing the words are good enough.
